/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bomgvxeykbasqcuwkcaw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvbWd2eGV5a2Jhc3FjdXdrY2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzQ3MjEsImV4cCI6MjA2OTMxMDcyMX0.EJKZ-Dh_lbMKDYtdJYWTUrqexkRPzII2-EdhbSbO9eM"